package com.seniorconnect.security;

import com.seniorconnect.auth.security.JwtService;
import com.seniorconnect.auth.security.RsaKeyProvider;
import io.jsonwebtoken.Claims;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.Environment;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class RsaKeyPersistenceAndAuditHardenTest {

    @Autowired
    private Environment environment;

    @Test
    @DisplayName("Gap 1 Evidence: Persistent RSA keys survive server restart and validate tokens across restarts")
    void testRsaKeyPersistenceAcrossSimulatedRestarts() throws Exception {
        java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("test-rsa-keys");

        // Generate real 2048-bit RSA key pair and persist to PEM files
        java.security.KeyPairGenerator keyGen = java.security.KeyPairGenerator.getInstance("RSA");
        keyGen.initialize(2048);
        java.security.KeyPair kp = keyGen.generateKeyPair();

        java.nio.file.Path privateKeyFile = tempDir.resolve("private.pem");
        java.nio.file.Path publicKeyFile = tempDir.resolve("public.pem");

        String privatePem = "-----BEGIN PRIVATE KEY-----\n" +
                java.util.Base64.getMimeEncoder(64, new byte[]{'\n'}).encodeToString(kp.getPrivate().getEncoded()) +
                "\n-----END PRIVATE KEY-----";
        String publicPem = "-----BEGIN PUBLIC KEY-----\n" +
                java.util.Base64.getMimeEncoder(64, new byte[]{'\n'}).encodeToString(kp.getPublic().getEncoded()) +
                "\n-----END PUBLIC KEY-----";

        java.nio.file.Files.writeString(privateKeyFile, privatePem);
        java.nio.file.Files.writeString(publicKeyFile, publicPem);

        String privateKeyPath = privateKeyFile.toAbsolutePath().toString();
        String publicKeyPath = publicKeyFile.toAbsolutePath().toString();

        // Instance A (First boot before restart)
        RsaKeyProvider instanceA = new RsaKeyProvider(environment);
        ReflectionTestUtils.setField(instanceA, "privateKeyPath", privateKeyPath);
        ReflectionTestUtils.setField(instanceA, "publicKeyPath", publicKeyPath);
        instanceA.init();

        JwtService jwtServiceA = new JwtService(instanceA, 900L, "seniorconnect-auth-server");

        UUID userId = UUID.randomUUID();
        com.seniorconnect.user.entity.User testUser = new com.seniorconnect.user.entity.User(
                userId,
                "student@galgotiacollege.edu.in",
                "Senior Mentor",
                com.seniorconnect.user.model.Role.JUNIOR,
                "Information Technology",
                5,
                false,
                java.time.Instant.now(),
                null
        );
        String tokenBeforeRestart = jwtServiceA.generateAccessToken(testUser);

        // Instance B (Second boot after simulated restart with same persistent keys)
        RsaKeyProvider instanceB = new RsaKeyProvider(environment);
        ReflectionTestUtils.setField(instanceB, "privateKeyPath", privateKeyPath);
        ReflectionTestUtils.setField(instanceB, "publicKeyPath", publicKeyPath);
        instanceB.init();

        JwtService jwtServiceB = new JwtService(instanceB, 900L, "seniorconnect-auth-server");

        // Validate token generated by Instance A using Instance B
        Claims validatedClaims = jwtServiceB.parseAndValidateToken(tokenBeforeRestart);
        assertThat(validatedClaims).isNotNull();
        assertThat(jwtServiceB.extractUserId(validatedClaims)).isEqualTo(userId);
        assertThat(jwtServiceB.extractRole(validatedClaims)).isEqualTo(com.seniorconnect.user.model.Role.JUNIOR);
        assertThat(jwtServiceB.extractEmail(validatedClaims)).isEqualTo("student@galgotiacollege.edu.in");
    }
}
