package com.seniorconnect.security;

import com.seniorconnect.auth.security.JwtService;
import com.seniorconnect.auth.security.RsaKeyProvider;
import io.jsonwebtoken.Claims;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.Environment;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class RsaKeyPersistenceAndAuditHardenTest {

    @Autowired
    private Environment environment;

    @Test
    @DisplayName("Gap 1 Evidence: Persistent RSA keys survive server restart and validate tokens across restarts")
    void testRsaKeyPersistenceAcrossSimulatedRestarts() {
        String privateKeyPath = "keys/private.pem";
        String publicKeyPath = "keys/public.pem";

        // Instance A (First boot before restart)
        RsaKeyProvider instanceA = new RsaKeyProvider(environment);
        ReflectionTestUtils.setField(instanceA, "privateKeyPath", privateKeyPath);
        ReflectionTestUtils.setField(instanceA, "publicKeyPath", publicKeyPath);
        instanceA.init();

        JwtService jwtServiceA = new JwtService(instanceA, 900L, "seniorconnect-auth-server");

        UUID userId = UUID.randomUUID();
        com.seniorconnect.user.entity.User testUser = new com.seniorconnect.user.entity.User(
                userId,
                "student@galgotiacollege.edu.in",
                "Senior Mentor",
                com.seniorconnect.user.model.Role.JUNIOR,
                "Information Technology",
                5,
                false,
                java.time.Instant.now(),
                null
        );
        String tokenBeforeRestart = jwtServiceA.generateAccessToken(testUser);

        // Instance B (Second boot after simulated restart with same persistent keys)
        RsaKeyProvider instanceB = new RsaKeyProvider(environment);
        ReflectionTestUtils.setField(instanceB, "privateKeyPath", privateKeyPath);
        ReflectionTestUtils.setField(instanceB, "publicKeyPath", publicKeyPath);
        instanceB.init();

        JwtService jwtServiceB = new JwtService(instanceB, 900L, "seniorconnect-auth-server");

        // Validate token generated by Instance A using Instance B
        Claims validatedClaims = jwtServiceB.parseAndValidateToken(tokenBeforeRestart);
        assertThat(validatedClaims).isNotNull();
        assertThat(jwtServiceB.extractUserId(validatedClaims)).isEqualTo(userId);
        assertThat(jwtServiceB.extractRole(validatedClaims)).isEqualTo(com.seniorconnect.user.model.Role.JUNIOR);
        assertThat(jwtServiceB.extractEmail(validatedClaims)).isEqualTo("student@galgotiacollege.edu.in");
    }
}
