package com.seniorconnect.audit.model;

public enum AuditEventType {
    AUTH_OTP_REQUESTED,
    AUTH_OTP_FAILED,
    AUTH_OTP_VERIFIED,
    AUTH_TOKEN_ISSUED,
    AUTH_TOKEN_REFRESHED,
    AUTH_TOKEN_REPLAY_DETECTED,
    AUTH_LOGOUT,
    REVEAL_REQUESTED,
    REVEAL_ACCEPTED,
    REVEAL_REJECTED,
    QUERY_CREATED,
    RESPONSE_POSTED,
    REPORT_SUBMITTED,
    USER_SOFT_SUSPENDED,
    TAG_VERIFIED,
    ADMIN_ACTION
}
